# Generated by Django 4.1.3 on 2023-05-06 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('myauthentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtestquetion',
            name='company',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myauthentication.companyprofile'),
        ),
        migrations.AddField(
            model_name='jobfilterquetion',
            name='company',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myauthentication.companyprofile'),
        ),
        migrations.AddField(
            model_name='jobapplicationdocmentation',
            name='job_applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobapplicant'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='jobseekers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myauthentication.jobseekerprofile'),
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myauthentication.companyprofile'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_filter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobfilterquetion'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_test',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobtestquetion'),
        ),
        migrations.AddField(
            model_name='filterquetionoption',
            name='job_filter_quetion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobfilterquetion'),
        ),
        migrations.AddField(
            model_name='filterquetionmultichoicequetion',
            name='job_filter_quetion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobfilterquetion'),
        ),
        migrations.AddField(
            model_name='filterquetionfillingap',
            name='job_filter_quetion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobfilterquetion'),
        ),
    ]
