# Generated by Django 4.1.3 on 2023-05-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicant',
            name='has_been_invited_for_medicals',
            field=models.BooleanField(default=False),
        ),
    ]
