# Generated by Django 4.1.3 on 2023-07-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobapplicant_has_been_invited_for_medicals'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employement_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract')], default='full_time', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='generic_skills',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='money_sign',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='professional_path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='required_experience',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='technical_skills',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
