# Generated by Django 4.1.3 on 2023-07-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_employement_type_job_generic_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterquetionfillingap',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='filterquestion/%d/'),
        ),
        migrations.AddField(
            model_name='filterquetionmultichoicequetion',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='filterquestion/%d/'),
        ),
        migrations.AddField(
            model_name='filterquetionoption',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='filterquestion/%d/'),
        ),
        migrations.AddField(
            model_name='testquetionfillingap',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='testquestion/%d/'),
        ),
        migrations.AddField(
            model_name='testquetionmultichoicequetion',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='testquestion/%d/'),
        ),
        migrations.AddField(
            model_name='testquetionoption',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='testquestion/%d/'),
        ),
    ]
