# Generated by Django 4.1.3 on 2023-07-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_jobinvitationletter_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtestquetion',
            name='suitable',
            field=models.IntegerField(default=21),
        ),
    ]
