# Generated by Django 4.1.3 on 2023-10-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_jobapplicant_created_at_jobapplicant_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicant',
            name='acceptance_letter',
            field=models.TextField(default='<h1>Hello world</h1>'),
        ),
    ]
