# Generated by Django 4.1.3 on 2023-05-06 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('interview', '0001_initial'),
        ('myauthentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackcandidateinterviewinvitation',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myauthentication.jobseekerprofile'),
        ),
        migrations.AddField(
            model_name='interview',
            name='company',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myauthentication.companyprofile'),
        ),
        migrations.AddField(
            model_name='interview',
            name='job',
            field=models.OneToOneField(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AddField(
            model_name='candidateinterviewsheet',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interview'),
        ),
        migrations.AddField(
            model_name='candidateinterviewsheet',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myauthentication.jobseekerprofile'),
        ),
        migrations.AddField(
            model_name='candidateinterviewsheet',
            name='panelist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myauthentication.panelistprofile'),
        ),
    ]
