# Generated by Django 4.1.3 on 2023-07-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicals', '0002_trackcandidatejobmedicalsinvitation_interview_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackcandidatejobmedicalsinvitation',
            name='interview_link',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
