# Generated by Django 4.1.3 on 2023-05-06 10:07

import cloudinary_storage.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('full_name', models.TextField()),
                ('user_type', models.CharField(choices=[('company', 'Company'), ('job_seakers', 'Job Seakers'), ('hr', 'Hr'), ('admin', 'Admin'), ('panelist', 'Panelist')], max_length=20)),
                ('profile_image', models.ImageField(upload_to='profile_image/%d/')),
                ('phone_number', models.CharField(max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=200)),
                ('organisation_name_shortname', models.CharField(default='short', max_length=30, unique=True)),
                ('industry', models.CharField(max_length=20)),
                ('organisation_size', models.IntegerField(default=0)),
                ('location', models.TextField()),
                ('official_mail', models.EmailField(default=None, max_length=254, null=True)),
                ('addresses', models.TextField()),
                ('official_phone', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PanelistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ManyToManyField(to='myauthentication.companyprofile')),
                ('job', models.ManyToManyField(to='jobs.job')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(default=None, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='job_seeker_cv/%d/%m')),
                ('notify_me_on', models.TextField(blank=True, default='')),
                ('first_name', models.CharField(default=' ', max_length=500)),
                ('middle_name', models.CharField(default=' ', max_length=500)),
                ('last_name', models.CharField(default=' ', max_length=500)),
                ('phone_number', models.CharField(default=' ', max_length=500)),
                ('email', models.CharField(default=' ', max_length=500)),
                ('addresse', models.CharField(default=' ', max_length=500)),
                ('city', models.CharField(default=' ', max_length=500)),
                ('state', models.CharField(default=' ', max_length=500)),
                ('country_of_residence', models.CharField(default=' ', max_length=500)),
                ('linkdin', models.URLField(blank=True, default=None, null=True)),
                ('twitter', models.URLField(blank=True, default=None, null=True)),
                ('personal_statement', models.TextField(default='I am Good')),
                ('education', models.JSONField(default=list)),
                ('experience', models.JSONField(default=list)),
                ('certificaton', models.JSONField(default=list)),
                ('refrences', models.JSONField(default=list)),
                ('has_updated_cv', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HrProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myauthentication.companyprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
