# Generated by Django 4.1.3 on 2023-05-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauthentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_image/%d/'),
        ),
    ]
