# Generated by Django 4.1.3 on 2023-05-26 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        ('myauthentication', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('company', 'Company'), ('job_seakers', 'Job Seakers'), ('hr', 'Hr'), ('admin', 'Admin'), ('panelist', 'Panelist'), ('medic', 'Medic')], max_length=20),
        ),
        migrations.CreateModel(
            name='MedicalRepProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.TextField()),
                ('hospital_phone', models.CharField(blank=True, default=True, max_length=12, null=True)),
                ('hospital_email', models.EmailField(blank=True, default=True, max_length=12, null=True)),
                ('company', models.ManyToManyField(to='myauthentication.companyprofile')),
                ('job', models.ManyToManyField(to='jobs.job')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
