# Generated by Django 4.1.3 on 2023-10-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauthentication', '0003_alter_user_user_type_medicalrepprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='industry',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='organisation_name_shortname',
            field=models.CharField(default='short', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('company', 'Company'), ('job_seakers', 'Job Seakers'), ('hr', 'Hr'), ('admin', 'Admin'), ('panelist', 'Panelist'), ('medic', 'Medic')], max_length=25),
        ),
    ]
